export const CALCULATOR_ACTIONS = {
    CLEAR_CALCULATOR: 'CLEAR_CALCULATOR',
    ADD_VARIABLE: 'ADD_VARIABLE',
    SET_OPERATION: 'SET_OPERATION',
    SET_RESULT: 'SET_RESULT',
    SET_CURRENT_VARIABLE: 'SET_CURRENT_VARIABLE',
    CALCULATE_RESULT: 'CALCULATE_RESULT'
}